SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE measurements (
  id int(10) UNSIGNED NOT NULL,
  sensor_id int(10) UNSIGNED NOT NULL,
  temperature float DEFAULT NULL,
  pressure float UNSIGNED DEFAULT NULL,
  rain int(10) UNSIGNED DEFAULT NULL,
  humidity float UNSIGNED DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moisture (
  id bigint(20) UNSIGNED NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  moisture01 smallint(6) NOT NULL,
  moisture02 smallint(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE sensors (
  id int(11) UNSIGNED NOT NULL,
  description varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  geo_lat double DEFAULT NULL,
  gep_long double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


ALTER TABLE measurements
  ADD PRIMARY KEY (id),
  ADD KEY sensor_id (sensor_id);

ALTER TABLE moisture
  ADD PRIMARY KEY (id);

ALTER TABLE sensors
  ADD PRIMARY KEY (id);


ALTER TABLE measurements
  MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE moisture
  MODIFY id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE sensors
  MODIFY id int(11) UNSIGNED NOT NULL AUTO_INCREMENT;


ALTER TABLE measurements
  ADD CONSTRAINT measurements_ibfk_1 FOREIGN KEY (sensor_id) REFERENCES sensors (id) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
